## Snakefile


    ## module load snakemake/5.2.2
    ## snakemake -np TARGET


## globals
anno = '/scratch/chd5n/aneuploidy/raw-data/annotations/'


rule write_annotation:
    input:
        'gdc_write_anno.py'
    output:
        anno + 'pheno.tsv',
        anno + 'manifest.tsv'
    shell:
        'python {input}'





# ## example format
# rule write_annotation:
#     input:
#         "data/genome.fa",
#         "data/samples/A.fastq"
#     output:
#         "mapped_reads/A.bam"
#     shell:
#         "bwa mem {input} | samtools view -Sb - > {output}"
